<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__username</name>
   <tag></tag>
   <elementGuidId>3eeb2960-7bb8-4d55-852e-17b90cef816a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputusername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputusername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe37affe-31b2-4e17-a660-af15c20aad03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input</value>
      <webElementGuid>c45920b2-863d-467a-95be-697940f74437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputusername</value>
      <webElementGuid>73d2b26f-15b5-4c70-984b-a2cbfb2c7b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e484bf5-641f-419f-9e12-a625c09ca5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>c39d80db-1623-4b2e-8d9a-ec2572c93076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tell us your email address</value>
      <webElementGuid>5aafd234-ae37-405f-a4fc-3009545e6bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputusername&quot;)</value>
      <webElementGuid>b49e1ffd-2914-4a43-bcc3-cc187505a91b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputusername']</value>
      <webElementGuid>77c66bbe-ad0a-4b60-961d-4265e3915026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/div/div/div/input</value>
      <webElementGuid>ce58666d-b7df-4d66-a6bc-bf1120a840a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6e0fc59c-ef21-4c35-bf60-ac7323a24ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputusername' and @type = 'text' and @name = 'username' and @placeholder = 'Tell us your email address']</value>
      <webElementGuid>ac74c30a-0820-44c0-85b4-91781bfb8f17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
