<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>operationsCard</name>
   <tag></tag>
   <elementGuidId>5da9a57a-7ad5-45f6-989c-5ff15da540ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class=' agent_home']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3590379-ce01-4b37-b557-d11e6daa4391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-text</value>
      <webElementGuid>13a63e82-780f-4fab-8878-12d56f243054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operations</value>
      <webElementGuid>a96dccb8-df65-4b10-b4f3-6fe7d4a1df3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;navigation-page d-flex justify-content-center align-items-center&quot;]/div[@class=&quot;landing_border-container&quot;]/div[@class=&quot;card welcome-card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-flex button-container&quot;]/button[@class=&quot;operation_home&quot;]/span[@class=&quot;button-text&quot;]</value>
      <webElementGuid>dac7fdbb-bade-45ab-98fd-2126fa16b231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/button/span</value>
      <webElementGuid>2216f536-beb1-4d47-91fc-f6ce34fff629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to the ContactCenter+'])[1]/following::span[1]</value>
      <webElementGuid>1ad4838d-a264-4302-9f1e-9ff4371053a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent'])[1]/preceding::span[1]</value>
      <webElementGuid>262d394c-47a9-4dc3-9105-be935e3d92ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::span[2]</value>
      <webElementGuid>649496f3-5c21-46ae-a177-fe225c66715a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Operations']/parent::*</value>
      <webElementGuid>b0f8e8eb-128f-44cd-bc06-cc411658c4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>f412e85f-0683-41c3-beba-1fc37b748b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Operations' or . = 'Operations')]</value>
      <webElementGuid>7b015020-6b1d-438f-ba76-a8998e9f3184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
